version: '3.7'

services: 
    mongodb_container:
        image: mongo:latest
        container_name: mongodb_container
        volumes:
            - dbdata:/data/db
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"

volumes:
    dbdata:
